# Generated by Django 5.1.2 on 2024-10-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homefind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
    ]
