# Generated by Django 5.1.2 on 2024-10-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homefind", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realestate",
            name="pyeongsu",
        ),
        migrations.RemoveField(
            model_name="realestate",
            name="spec_address",
        ),
        migrations.AddField(
            model_name="realestate",
            name="rent_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_name",
            field=models.CharField(max_length=50),
        ),
    ]
