# Generated by Django 5.1.2 on 2024-10-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homefind", "0003_alter_realestate_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="type",
            field=models.CharField(
                choices=[
                    ("villa", "villa"),
                    ("officetel", "officetel"),
                    ("oneroom", "oneroom"),
                ],
                default="oneroom",
                max_length=50,
            ),
        ),
    ]
